mysite2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tradeJpyUsd/',include('tradeJpyUsd.urls',namespace="tradeJpyUsd")),
]

tradeJpyUsd/urls.py
from django.urls import path

from . import views
app_name = 'tradeJpyUsd'
urlpatterns = [
    path('',views.index,name='index'),
    path('Sma',views.Sma,name='Sma'),
]

tradeJpyUsd/models.py
from django.db import models

# Create your models here.
class Inout(models.Model):
    short = models.IntegerField(default=5,verbose_name = "短い移動平均線")
    long = models.IntegerField(default=14,verbose_name = "長い移動平均線")
    val = models.IntegerField(default = 30,verbose_name = "取引量")
    start = models.IntegerField(default=1000000,verbose_name="初期投資額")

tradeJpyUsd/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    context={}
    return render(request,'tradeJpyUsd/index.html',context)
def Sma(request):
    return render(request,'tradeJpyUsd/results.html')

tradeJpyUsd/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset = 'utf-8'>
        <meta name='viewport' content='width=device-width ,initial-scale=1,shrink-to-fit=no'> 
		<title>JpyUsd Simulation</title>
        <link rel ='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
		<style>			body {
				padding-top: 80px;
			}
		</style>
	</head>
	<body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class='navbar-brand' href='{% url "tradeJpyUsd:index" %}'>JpyUsd Simulation</a>
        </nav>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
	</body>
</html>

tradeJpyUsd/templates/tradeJpyUsd/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h1>TradeJpyUsd</h2>
<p>ここでは、USDとJPYをインジケータを用いてトレードした場合どうなるのか、シミュレーションをします。</p>
<form action={% url "TradeJpyUsd:Sma" %}>
<button type = 'submit' value = "Simulation">
</form>
{% endblock content%}

tradeJpyUsd/templates/tradeJpyUsd/results.html
{% extends base.html %}
{% load bootstrap4 %}
{% block content %}
結果がでたよ
{% endblock content %}